version: '3.4'
services:
  php:
    image: jamesmalin/laravel-api-react-jwt:1.0.2
    environment:
      APP_NAME: laravel-api-react-jwt
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: 
      APP_LOG_LEVEL: debug
      APP_URL: "http://localhost"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: apiLaravelDocker
      DB_USERNAME: apiLaravelDocker
      DB_PASSWORD: apiLaravelDocker
      XDEBUG_MODE: 1
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - .:/laravel-api-react-jwt

  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: apiLaravelDocker
      MYSQL_USER: apiLaravelDocker
      MYSQL_PASSWORD: apiLaravelDocker
      MYSQL_ROOT_PASSWORD: apiLaravelDocker
    volumes:
      - .docker/local-mysql-datadir:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
