#!/bin/bash

# ENVIRONMENT VARIABLES ----------------------------------
	cp /laravel-api-react-jwt/.env.example /laravel-api-react-jwt/.env

# Xdebug ----------------------------------------------------
	if [ "${XDEBUG_MODE}" == 1 ] ; then
		mkdir -p /laravel-api-react-jwt/.docker/local-mysql-datadir
		echo 'Installs require-dev dependencies'
		composer install --no-scripts
		echo 'Permissions'
		chmod 777 -R /laravel-api-react-jwt/storage
		echo 'Installing XDebug...'
		pecl install xdebug && docker-php-ext-enable xdebug
		echo 'XDebug installed!'
	fi

# WAIT FOR MYSQL READY -----------------------------------
	echo 'Checking MySql...'
	while !(mysqladmin ping --host=$DB_HOST)
	do
		sleep 1
		echo 'Waiting for MySql...'
	done
	echo 'MySql ready!'

# MIGRATIONS -----------------------------------
	echo 'Running Migrations...'
	cd /laravel-api-react-jwt
	php artisan key:generate
	php artisan jwt:secret -f
	php artisan migrate
	echo 'Migrations done!'

# APACHE -----------------------------------
# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi
exec "$@"